workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      android_signing:
        - keystore_credentials
      groups:
        - google_play_credentials
      vars:
        PACKAGE_NAME: "com.seovulf.randmapp"
        GOOGLE_PLAY_TRACK: internal
      flutter: stable

    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true

      - name: Run unit tests
        script: |
          flutter test test/unit_test.dart

      - name: Run widget tests
        script: |
          flutter test test/widget_test.dart

      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt

    publishing:
      email:
        recipients:
          - seovulf@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GOOGLE_PLAY_JSON_KEY
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true