default_platform(:android)

platform :android do
  desc "Deploy to Google Play Internal Testing"
  lane :deploy do
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end